"""empty message

Revision ID: 4bf97cd0f528
Revises: 
Create Date: 2017-10-13 22:11:04.753767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf97cd0f528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dados_Dpt',
    sa.Column('id_Dados_Dpt', sa.Integer(), nullable=False),
    sa.Column('status_Dpt', sa.Boolean(), nullable=True),
    sa.Column('nivel_Tensao', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_Dados_Dpt')
    )
    op.create_table('Tipos_Dpts',
    sa.Column('Tipo_Dpt_id', sa.Integer(), nullable=False),
    sa.Column('nome_Tipo_Dpt', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Tipo_Dpt_id')
    )
    op.create_table('Usuario',
    sa.Column('id_User', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('perfil', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_User')
    )
    op.create_table('Dispositivos',
    sa.Column('id_Dpt', sa.Integer(), nullable=False),
    sa.Column('tipo_dpt_Id', sa.Integer(), nullable=True),
    sa.Column('nome_Dpt', sa.String(length=30), nullable=True),
    sa.Column('URL_Foto_Dpt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_dpt_Id'], ['Tipos_Dpts.Tipo_Dpt_id'], ),
    sa.PrimaryKeyConstraint('id_Dpt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dispositivos')
    op.drop_table('Usuario')
    op.drop_table('Tipos_Dpts')
    op.drop_table('Dados_Dpt')
    # ### end Alembic commands ###
